version: "3.8"

services:
  # Backend (NestJS)
  backend:
    build: ./chronobackend
    container_name: nestjs-app
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./chronobackend/.env
    depends_on:
      db:
        condition: service_healthy

  # Frontend (Next.js)
  frontend:
    build: ./chronofrontend
    container_name: nextjs-frontend
    restart: always
    env_file:
      - ./chronofrontend/.env
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./chronofrontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  # Database (MySQL)
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: samih123@
      MYSQL_DATABASE: chrono_carto
      MYSQL_USER: samih_jeridi
      MYSQL_PASSWORD: samih123@
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psamih123@"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Nginx reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt

  # Certbot for SSL
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot 
      --webroot-path=/var/www/certbot 
      --email wajihsayes@gmail.com 
      --agree-tos 
      --no-eff-email 
      -d chronocarto.tn 
      -d www.chronocarto.tn"

volumes:
  mysql_data:
