version: "3.8"

services:
  # Backend (NestJS)
  backend:
    build: ./chronobackend
    container_name: nestjs-app
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./chronobackend/.env
    depends_on:
      db:
        condition: service_healthy

  # Frontend (Next.js)
  frontend:
    build: ./chronofrontend
    container_name: nextjs-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./chronofrontend/.env
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./chronofrontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  # Database (MySQL)
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: samih123@
      MYSQL_DATABASE: chrono_carto
      MYSQL_USER: samih_jeridi
      MYSQL_PASSWORD: samih123@
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psamih123@"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mysql_data:

