version: "3.8"

services:
  # Backend (NestJS)
  backend:
    build: ./chronobackend
    container_name: nestjs-app
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./chronobackend/.env
    depends_on:
      - db

  # Frontend (Next.js)
  frontend:
    build: ./chronofrontend
    container_name: nextjs-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./chronofrontend/.env
    depends_on:
      - app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  # Database (Postgres)
  db:
    image: postgres:15
    container_name: nestjs-db
    restart: always
    environment:
      POSTGRES_USER: samih_jeridi
      POSTGRES_PASSWORD: samih123@
      POSTGRES_DB: chrono_carto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
